from enum import StrEnum


class NodeType(StrEnum):
    REQ = "REQ"
    CRU = "CRU"
    CHUNK = "CHUNK"
    TEST = "TEST"
    RUN = "RUN"
    DEFECT = "DEFECT"


class EdgeType(StrEnum):
    SUPPORTED_BY = "SUPPORTED_BY"
    PARENT_OF = "PARENT_OF"
    DECOMPOSED_TO = "DECOMPOSED_TO"
    TESTS = "TESTS"
    EVIDENCE_FOR = "EVIDENCE_FOR"
    EXECUTED_AS = "EXECUTED_AS"
    RAISED_AS = "RAISED_AS"
    AFFECTS = "AFFECTS"
    INFERRED_SUPPORTED_BY = "INFERRED_SUPPORTED_BY"
